title = "To Do List"

[[libraries]]
name = "ToDo"

[[libraries.structs]]
name = "Item"
fields = [
  { name = "Done", type = "bit" },
  { name = "Hidden", type = "bit" },
  { name = "Title", type = "text" },
]
